"""add_default_value

Revision ID: 6844a21036a2
Revises: fcbc5ceac1aa
Create Date: 2024-08-30 12:31:22.519126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6844a21036a2'
down_revision: Union[str, None] = 'fcbc5ceac1aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    nullable=False,
                    server_default="false"
                    )
    op.alter_column('category', 'level',
                    existing_type=sa.INTEGER(),
                    nullable=False,
                    server_default="100"
                    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    nullable=False,
                    server_default=None
                    )
    op.alter_column('category', 'level',
                    existing_type=sa.INTEGER(),
                    nullable=False,
                    server_default=None
                    )
    pass
    # ### end Alembic commands ###
