"""add_product_line_attribute_value_table

Revision ID: 8025a8173744
Revises: b55a1fb29079
Create Date: 2024-09-02 16:19:22.455507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8025a8173744'
down_revision: Union[str, None] = 'b55a1fb29079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_line_attribute_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribute_value_id', sa.Integer(), nullable=False),
    sa.Column('product_line_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_value_id'], ['attribute_value.id'], ),
    sa.ForeignKeyConstraint(['product_line_id'], ['product_line.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attribute_value_id', 'product_line_id', name='uq_product_line_attribute_value')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_line_attribute_value')
    # ### end Alembic commands ###
