"""category_update

Revision ID: a3ae758e758c
Revises: 54e1776ada80
Create Date: 2024-08-29 18:31:39.960683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3ae758e758c'
down_revision: Union[str, None] = '54e1776ada80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('category', sa.Column('slug', sa.String(length=120), nullable=True))
    op.add_column('category', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('category', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('category', sa.Column('parent_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'parent_id')
    op.drop_column('category', 'level')
    op.drop_column('category', 'is_active')
    op.drop_column('category', 'slug')
    op.drop_column('category', 'name')
    # ### end Alembic commands ###
