"""add_unique_constraints

Revision ID: ded88ee04958
Revises: 6844a21036a2
Create Date: 2024-08-30 12:55:26.029350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded88ee04958'
down_revision: Union[str, None] = '6844a21036a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_category_name_level', 'category', ['name', 'level'])
    op.create_unique_constraint('uq_category_slug', 'category', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_category_slug', 'category', type_='unique')
    op.drop_constraint('uq_category_name_level', 'category', type_='unique')
    # ### end Alembic commands ###
