"""update_constraints

Revision ID: fcbc5ceac1aa
Revises: 3ed9b4bbb6c6
Create Date: 2024-08-30 12:23:26.254998

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "fcbc5ceac1aa"
down_revision: Union[str, None] = "3ed9b4bbb6c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        constraint_name="name_length_check",
        table_name="category",
        condition="LENGTH(name) > 0",
    )
    op.create_check_constraint(
        constraint_name="slug_length_check",
        table_name="category",
        condition="LENGTH(slug) > 0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        constraint_name="name_length_check", table_name="your_table_name", type_="check"
    )
    op.drop_constraint(
        constraint_name="slug_length_check", table_name="your_table_name", type_="check"
    )
    # ### end Alembic commands ###
